import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Download from "../assets/downoad";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Oluwafemi's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:px-16 px-5 ">
        <Navbar />

        <div className="lg:flex items-center justify-between mt-48">
          <div className="lg:w-[50%] flex flex-col gap-3 items-start">
            <p className="">Hello,</p>
            <p className="text-[30px] md:text-[44px] lg:leading-[50px] font-semibold ">
              I am Oluwafemi, a{" "}
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-[#F40076] to-[#342711]">
                Frontend Engineer
              </span>
              . <br />I am a{" "}
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-[#F40076] to-[#342711]">
                solution-driven
              </span>{" "}
              developer.
            </p>
            <p>
              I am a seasoned front-end developer with a wealth of experience in
              creating and nurturing web applications. My journey is defined by
              my expertise in various cutting-edge technologies, including
              React, JavaScript, TypeScript, VS Code, Git & GitHub, Tailwind,
              Next.js, CSS, HTML, and Redux Toolkit. These skills are a
              testament to my unwavering commitment to staying at the forefront
              of web development.
            </p>
            <button className="text-black bg-white p-3 rounded-md flex items-center gap-2">
              Download Resume <Download />
            </button>
          </div>
          <div className="lg:w-[45%]">
            <video autoPlay muted loop className="">
              <source src="/animae.mp4" type="video/mp4" />
            </video>
          </div>
        </div>
        <About />
        <Projects />
        <Contact />
      </main>
    </>
  );
}
